service: cvs-tsk-cert-gov-notify

provider:
  name: aws
  runtime: nodejs18.x
  tracing:
    lambda: true # enable tracing
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - s3:
          bucket: cvs-signature
          event: s3:ObjectCreated:Put
