invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://localhost:3000
    functions:
      testResults:
        name: cvs-svc-test-results
        mock: tests/resources/test-results-response.json
      techRecords:
        name: cvs-svc-technical-records
        mock: tests/resources/tech-records-response.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      testResults:
        name: test-results-${BRANCH}
      techRecords:
        name: technical-records-${BRANCH}
s3:
  local:
    endpoint: http://localhost:7000
    s3ForcePathStyle: true
  remote: {}
notify:
  api_key:
  templateId: ff36dae2-937e-4883-9e25-e776fa6af665
